dist: xenial
sudo: required

language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - tip

script:
  - sudo -E env "PATH=$PATH" go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
